---
title: "Introduction to Bayesian Statistics with R"
subtitle: "0: Overview"
author: "Jack Kuipers"
date: "5 May 2025"
runtime: shiny
output:
  ioslides_presentation: 
    css: ibswr.css
    incremental: true
    widescreen: true
    smaller: true
    fig_width: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
start_date <- as.Date("05-05-25", format = "%d-%m-%y")
f_date <- function(d, m, k=0) {
  format(d+m*1+k, "%d-%m-%y")
}
```

## Overview {.build}

<div>

8 sessions - 2 recorded (with lecture notes), 6 in-person

>- Interactive lecture each session (c. 45 mins) **Jack Kuipers**
>- written in R shiny
</div>

<div>
<span class="question">Questions on the slides</span>

>- <span class="answer">think about and work on the question <br> or form small groups and discuss</span>
</div>

<div>
Every session has an associated exercise sheet

>- allocated time within each session (c. 1 hr)
>- hand in later for marking for credit points **Wandrille Duchemin**
>- short review at the end of each session (c. 15 mins) **Wandrille Duchemin**
</div>

<div>
Newish course

>- feedback always highly appreciated
</div>

<div>
Course material [https://github.com/sib-swiss/intro-bayesian-statistics-training]
</div>

## Topics {.build}

<div>
Course starts with a self-study phase

>- containing the first two sessions

These sessions

>- recap core concepts from frequentist statistics

<br>

</div>

<div>
<div class="centered">
<div style="width: 50%; display: inline-block">
| n | Topic |
|:-:|:-----:|
|1|t-test recap|
|2|p-values and confidence intervals|
</div>
</div>

<br>
<br>

Which we will later leverage to transition to Bayesian statistics
</div>

## Topics

Day 1: Bayesian beginnings, `r f_date(start_date, 0)`

<div class="centered">
<div style="width: 75%; display: inline-block">
| n | Topic | Breaks | Time |
|:-:|:-----:|:------:|:----:|
|0|Overview|--|9:00--9:15|
|3|Monte Carlo methods|--|9:15--11:30|
|--|(including)|Coffee|10:30--11:00|
|4|Bayesian first steps|--|11:30--14:30|
|--|(including)|Lunch|12:30--13:30|
|5|Bayesian t-tests|--|14:30--17:00|
|--|(including)|Coffee|15:30--16:00|
</div>
</div>

## Topics

Day 2: Bayesian regression, `r f_date(start_date, 1)`

<div class="centered">
<div style="width: 75%; display: inline-block">
| n | Topic | Breaks | Time |
|:-:|:-----:|:------:|:----:|
|6|Robust t-tests and priors|--|9:00--11:30|
|--|(including)|Coffee|10:30--11:00|
|7|Bayesian multiple regression|--|11:30--14:30|
|--|(including)|Lunch|12:30--13:30|
|8|Bayesian logistic regression|--|14:30--16:45|
|--|(including)|Coffee|15:30--16:00|
|9|Outlook|--|16:45--17:00|
</div>
</div>


## Learning outcomes and software {.build}

At the end of the course, participants should be able to:

* Recognise the core components of a Bayesian model
* List the main concepts of methods for Bayesian inference
* Implement a simple Bayesian model in R
* Interpret the results of a Bayesian model

You will need

>- latex [https://www.latex-project.org/get/]
>- R and Rstudio [https://www.r-project.org/ https://www.rstudio.com/]
>- Packages: rmarkdown, shiny, tidyverse (ggplot2, knitr, readr, ...)

And for the Bayesian regression

>- Rstan [https://mc-stan.org/users/interfaces/rstan]
>- brms [https://cran.r-project.org/web/packages/brms/index.html]

Link to course material [https://github.com/sib-swiss/intro-bayesian-statistics-training]


